name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_NAME: "test-maven-app"
  DOCKERHUB_USERNAME: "kunchalavikram"	  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SCM
      uses: actions/checkout@v3
    - name: list workspace contents
      run: ls -al ${{ github.workspace }}
    - name: Setup Java and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '11'
    - name: Package the Application
      run: |
        mvn -B package
        ls -al ${{ github.workspace }}/target
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: war-file
        path: target/*.war
        if-no-files-found: 'error'
        retention-days: 1 day

  dockerize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: target/*.war
      - name: Check the WAR file
        run: ls -al ${{ github.workspace }}/target		  
      - name: Dockerize the Application
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME}}:${{ github.run_number }} .
